# Generated by Django 2.1.7 on 2019-03-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title_name', models.CharField(max_length=500)),
                ('Citations', models.CharField(max_length=50)),
                ('CoAuthors', models.CharField(max_length=50)),
                ('Normalized_citations', models.CharField(max_length=50)),
            ],
        ),
    ]
